package org.white.green.developer


val degrees = listOf(
    "10th Grade",
    "12th Grade",
    "High School",
    "Bachelor's",
    "Master's",
    "PhD",
    "Diploma",
    "Associate Degree",
    "Certificate",
    "Doctorate (other than PhD)",
    "Postgraduate Diploma",
    "Postdoctoral Fellowship",
    "Professional Degree (e.g., MD, JD, LLB)",
    "Trade School Certification",
    "Vocational Training",
    "Foundation Degree",
    "Advanced Diploma",
    "Graduate Certificate",
    "Executive MBA (EMBA)",
    "Honours Degree",
    "Continuing Education",
    "Nursing Diploma",
    "Bachelor of Science in Nursing (BSN)",
    "Master of Science in Nursing (MSN)",
    "Doctor of Nursing Practice (DNP)",
    "Certified Nursing Assistant (CNA)",
    "Licensed Practical Nurse (LPN)",
    "Registered Nurse (RN)",
    "Other"
)


val countries = listOf(
    "🇮🇳 India",
    "🇦🇺 Australia",
    "🇨🇦 Canada",
    "🇵🇹 Portugal",
    "🇬🇧 United Kingdom (England)",
    "🇺🇸 United States",
    "🇦🇪 United Arab Emirates",
    "🇦🇷 Argentina",
    "🇧🇷 Brazil",
    "🇨🇳 China",
    "🇪🇬 Egypt",
    "🇪🇸 Spain",
    "🇫🇷 France",
    "🇩🇪 Germany",
    "🇮🇩 Indonesia",
    "🇮🇹 Italy",
    "🇯🇵 Japan",
    "🇲🇾 Malaysia",
    "🇲🇽 Mexico",
    "🇳🇬 Nigeria",
    "🇳🇿 New Zealand",
    "🇵🇰 Pakistan",
    "🇵🇭 Philippines",
    "🇵🇱 Poland",
    "🇷🇺 Russia",
    "🇸🇦 Saudi Arabia",
    "🇸🇬 Singapore",
    "🇰🇷 South Korea",
    "🇹🇭 Thailand",
    "🇹🇷 Turkey",
    "🇿🇦 South Africa"
)

val indianStates = listOf(
    "Haryana",
    "Uttar Pradesh (UP)",
    "Uttarakhand",
    "Punjab",
    "Himachal Pradesh",
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bihar",
    "Chhattisgarh",
    "Goa",
    "Gujarat",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "West Bengal"
)
